services:
  desktop:
    image: moicben/agi-engine:beta
    container_name: kasm-desktop
    platform: linux/arm64/v8     # Mac Apple Silicon (ARM64)
    shm_size: "2g"               # important for Chrome/Puppeteer stability
    environment:
      - VNC_PW=secret            # password for the noVNC login screen
      - TZ=Europe/Paris
    ports:
      - "6901:6901"             # noVNC web UI (http://localhost:6901)
      - "3000:3000"             # sample app port (e.g., Next.js / Express)
      - "5173:5173"             # sample dev port (e.g., Vite)
    volumes:
      - ./kasm-home:/home/kasm-user     # persist user home (installed tools, configs)
      - ./:/home/kasm-user/project      # mount your project into the desktop
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    security_opt:
      - apparmor:unconfined
    restart: unless-stopped